In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,])
print("Original array:")
arr=np.insert(arr,2,10)
print("array after inserting value is:\n",arr)

Original array:
array after inserting value is:
 [ 1  2 10  3  4  5]


In [8]:
import numpy as np
arr=np.arange(10)
print("Original array is:",arr)
print("shape",arr.shape)
arr1=np.delete(arr,5)
print("array after deleting value is:\n",arr1)
print("shape",arr1.shape)
arr1=np.delete(arr,[6,7])
print("array after deleting 6 and 7 is:",arr1)
print("shape:",arr.shape)
import numpy as np
arr= np.ones(10)
if(arr.size == 0):
  print("array is empty")
else:
  print("the array =", arr)

Original array is: [0 1 2 3 4 5 6 7 8 9]
shape (10,)
array after deleting value is:
 [0 1 2 3 4 6 7 8 9]
shape (9,)
array after deleting 6 and 7 is: [0 1 2 3 4 5 8 9]
shape: (10,)
the array = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
import numpy as np
arr_3d = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9], [10, 11, 12]]])
print("Original 3D array:\n", arr_3d)
print("Shape of original 3D array:", arr_3d.shape)
arr_1d = arr_3d.flatten()
print("\nConverted 1D array:\n", arr_1d)
print("Shape of converted 1D array:", arr_1d.shape)

Original 3D array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
Shape of original 3D array: (1, 4, 3)

Converted 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of converted 1D array: (12,)


In [7]:
print("array after deleting 6 and 7 is:",arr1)
print("shape:",arr.shape)
import numpy as np
arr= np.ones(10)
if(arr.size == 0):
  print("array is empty")
else:
  print("the array =", arr)

array after deleting 6 and 7 is: [0 1 2 3 4 5 8 9]
shape: (10,)
the array = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
import numpy as np
arr=np.arange(12).reshape(3,4)
print("the array is:",arr)
print("length of the array is:",arr.size)

the array is: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
length of the array is: 12


In [13]:
import numpy as np
arr=np.arange(11)
print("the array is:",arr)
index=np.where(arr==6)
print("the index value 6 is:",index[0])

the array is: [ 0  1  2  3  4  5  6  7  8  9 10]
the index value 6 is: [6]


In [15]:
import numpy as np
arr=np.array([4,0,9,1,6,8,2,3,7,5])
print("Original array:",arr)
arr.sort()
print("sorted array",arr)


Original array: [4 0 9 1 6 8 2 3 7 5]
sorted array [0 1 2 3 4 5 6 7 8 9]


In [19]:
import numpy as np
arr=np.array([4,0,9,1,6,8,2,3,7,5])
print("Original array:",arr)
arr.sort()
arr = arr[::-1]
print("Sorted array (descending):",arr)

Original array: [4 0 9 1 6 8 2 3 7 5]
Sorted array (descending): [9 8 7 6 5 4 3 2 1 0]


In [20]:
import numpy as np
arr=np.array([450,620,390,530,250,320,410])
arr_max=arr.max()
arr_min=arr.min()
arr=(arr-arr_min)/(arr_max-arr_min)
print("after normalization array is:",arr)

after normalization array is: [0.54054054 1.         0.37837838 0.75675676 0.         0.18918919
 0.43243243]


In [22]:
import numpy as np
arr=np.array([1,2,3,4])
print("original array:\n",arr)
print("transposed array is:",arr.T)

original array:
 [1 2 3 4]
transposed array is: [1 2 3 4]


In [23]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,1,0,2],[3,4,5,6]])
print("original array:\n",arr)
print("transposed array is:\n",np.transpose(arr))

original array:
 [[1 2 3 4]
 [5 6 7 8]
 [9 1 0 2]
 [3 4 5 6]]
transposed array is:
 [[1 5 9 3]
 [2 6 1 4]
 [3 7 0 5]
 [4 8 2 6]]


In [26]:
import numpy as np
arr_3d = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9], [10, 11, 12]]])
print("original array:\n",arr_3d)
print("transposed array is:\n",np.transpose(arr_3d))

original array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
transposed array is:
 [[[ 1]
  [ 4]
  [ 7]
  [10]]

 [[ 2]
  [ 5]
  [ 8]
  [11]]

 [[ 3]
  [ 6]
  [ 9]
  [12]]]


In [29]:
import numpy as np

arr_2d = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])
print("Original 2D array:\n", arr_2d)

print("\nDiagonals:")
print("  Main (k=0):", np.diag(arr_2d))
print("  Above (k=1):", np.diag(arr_2d, k=1))
print("  Below (k=-1):", np.diag(arr_2d, k=-1))

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonals:
  Main (k=0): [ 1  6 11 16]
  Above (k=1): [ 2  7 12]
  Below (k=-1): [ 5 10 15]


In [30]:
import numpy as np
arr3d=np.arange(27).reshape(3,3,3)
print("3d array is:",arr3d)
print("Daigonal elements for axis1=1 and axis2=2 are:")
print(arr3d.diagonal(axis1=1,axis2=2))

3d array is: [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Daigonal elements for axis1=1 and axis2=2 are:
[[ 0  4  8]
 [ 9 13 17]
 [18 22 26]]
